Repository Saitnbone/shop.co-project__frontend, pull requests merged in 2024-11, with the labels that each got.

#1 feat:/ Added a Readme file with a description for each layer of the application
  src/app/README.md
  src/assets/react.svg
  src/entities/README.md
  src/pages/README.md
  src/processes/README.md
  src/shared/README.md
  src/widgets/README.md
Labels: documentation

#2 Изменения
  index.html
  src/features/README.md
Labels: enhancement

#4 chore: Добавлено описание в файлах README.md
  src/app/App.css
  src/app/App.tsx
  src/app/README.md
  src/entities/README.md
  src/features/README.md
  src/main.tsx
  src/pages/README.md
  src/processes/README.md
  src/shared/README.md
  src/widgets/README.md
Labels: documentation

#13 Feat/ task 12
  package-lock.json
  package.json
  src/app/App.tsx
  src/index.css
  src/shared/ui/dropdown/Dropdown.module.scss
  src/shared/ui/dropdown/Dropdown.tsx
  src/shared/ui/dropdown/mock.ts
  src/widgets/header/ui/components/menu/Menu.module.scss
  src/widgets/header/ui/components/menu/Menu.tsx
Labels: enhancement

#17 feat:/ui Подготовить стили блока header под различные устройства
  .storybook/main.ts
  package-lock.json
  package.json
  src/app/App.css
  src/app/App.tsx
  src/index.css
  src/path.d.ts
  src/widgets/header/facade/facade.tsx
  src/widgets/header/index.tsx
  src/widgets/header/types.ts
  src/widgets/header/ui/Layout.tsx
  src/widgets/header/ui/components/menu/Menu.module.scss
  src/widgets/header/ui/components/menu/Menu.tsx
  src/widgets/header/ui/styles.module.scss
  tsconfig.app.json
  vite.config.ts
Labels: enhancement

#18 feat:ui/ Сделать блок с иконками профиля и корзины #10
  src/app/App.tsx
  src/widgets/header/ui/Layout.tsx
  src/widgets/header/ui/components/icons-block/CartIcon.tsx
  src/widgets/header/ui/components/icons-block/IconsBlock.tsx
  src/widgets/header/ui/components/icons-block/ProfileIcon.tsx
  src/widgets/header/ui/styles.module.scss
Labels: enhancement

#22 feat:/ Добавлена базовая разметка для старницы MainPage
  src/pages/MainPage/facade/facade.tsx
  src/pages/MainPage/index.ts
  src/pages/MainPage/ui/Layout.tsx
  src/pages/MainPage/ui/styles.module.scss
Labels: enhancement

#24 feat:/app Подключить роутинг для приложения #9
  src/app/App.tsx
  src/app/router/router.tsx
  src/main.tsx
  src/pages/MainPage/ui/Layout.tsx
  src/pages/index.ts
  src/shared/ui/logo/LogoUI.tsx
  src/shared/ui/logo/index.ts
Labels: enhancement

#30 Исправил стили в компонентах, сделал компонент поиска
  src/shared/ui/dropdown/Dropdown.module.scss
  src/shared/ui/dropdown/Dropdown.tsx
  src/widgets/header/ui/Layout.tsx
  src/widgets/header/ui/components/icons-block/SearchIcon.tsx
  src/widgets/header/ui/components/search-input/SearchInput.module.scss
  src/widgets/header/ui/components/search-input/SearchInput.tsx
  src/widgets/header/ui/styles.module.scss
Labels: enhancement

#46 feat:/ui Разработать кнопку-бургер в блоке header
  src/shared/ui/burger-icon/styles.module.scss
  src/shared/ui/logo/LogoUI.stories.ts
  src/stories/Button.stories.ts
  src/stories/Button.tsx
  src/stories/Configure.mdx
  src/stories/Header.stories.ts
  src/stories/Header.tsx
  src/stories/Page.stories.ts
  src/stories/Page.tsx
  src/stories/assets/accessibility.png
  src/stories/assets/accessibility.svg
  src/stories/assets/addon-library.png
  src/stories/assets/assets.png
  src/stories/assets/avif-test-image.avif
  src/stories/assets/context.png
  src/stories/assets/discord.svg
  src/stories/assets/docs.png
  src/stories/assets/figma-plugin.png
  src/stories/assets/github.svg
  src/stories/assets/share.png
  src/stories/assets/styling.png
  src/stories/assets/testing.png
  src/stories/assets/theming.png
  src/stories/assets/tutorials.svg
  src/stories/assets/youtube.svg
  src/stories/button.css
  src/stories/header.css
  src/stories/page.css
  src/widgets/header/ui/Layout.tsx
  src/widgets/header/ui/components/icons-block/BurgerIcon.tsx
  src/widgets/header/ui/components/icons-block/IconsBlock.tsx
  src/widgets/header/ui/components/icons-block/MobileSearchIcon.tsx
  src/widgets/header/ui/components/icons-block/SearchIcon.tsx
  src/widgets/header/ui/components/menu/Menu.tsx
  src/widgets/header/ui/components/search-input/SearchInput.module.scss
  src/widgets/header/ui/styles.module.scss
Labels: enhancement

#38 Feat/ task 37
  src/shared/assets/people.png
  src/shared/assets/star.svg
  src/widgets/cover/facade/facade.tsx
  src/widgets/cover/index.tsx
  src/widgets/cover/types.ts
  src/widgets/cover/ui/Layout.tsx
  src/widgets/cover/ui/components/advantages/Advantage-list.tsx
  src/widgets/cover/ui/components/advantages/Advantage.tsx
  src/widgets/cover/ui/components/advantages/style.module.scss
  src/widgets/cover/ui/mockCoverData.ts
  src/widgets/cover/ui/styles.module.scss
Labels: enhancement

#34 Добавил стили для root и main
  src/app/styles/global.scss
  src/pages/MainPage/ui/styles.module.scss
Labels: wontfix

#55 feat: Подключена секция приветствия для главной страницы
  src/pages/MainPage/facade/facade.tsx
  src/pages/MainPage/types.ts
  src/pages/MainPage/ui/Layout.tsx
Labels: enhancement
